[build]
  command = "gatsby build"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.12.0"
  YARN_VERSION = "4.1.1"

[context.production.environment]
  NODE_ENV = "production"
  GATSBY_ACTIVE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  GATSBY_ACTIVE_ENV = "development"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
